plugins {
  id "com.android.application"
  id "org.jetbrains.kotlin.android"
}

def repo = rootProject.projectDir.parentFile.parentFile

android {
  namespace = "to.holepunch.bare.bluetooth.test"
  compileSdk = 35

  defaultConfig {
    applicationId = "to.holepunch.bare.bluetooth.test"
    minSdk = 33
    targetSdk = 35
    versionCode = 1
    versionName = "1.0"

    ndk {
      abiFilters "arm64-v8a"
    }
  }

  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = "17"
  }

  sourceSets {
    main {
      jniLibs.srcDirs "src/main/addons", "libs/bare-kit/jni"
    }
  }
}

tasks.register("link", Exec) {
  workingDir repo

  commandLine([
    "node_modules/.bin/bare-link",
    "--host", "android-arm64",
    "--out", "test/test-app/app/src/main/addons"
  ])
}

tasks.register("linkTest", Exec) {
  workingDir repo

  commandLine([
    "node_modules/.bin/bare-link",
    "--host", "android-arm64",
    "--out", "test/test-app/app/src/main/addons",
    "node_modules/brittle"
  ])
}

tasks.register("pack", Exec) {
  workingDir repo

  commandLine([
    "node_modules/.bin/bare-pack",
    "--host", "android-arm64",
    "--linked",
    "--defer", "bare-cov",
    "--out", "test/test-app/app/src/main/assets/test.bundle",
    "test/test-app/test.js"
  ])
}

preBuild.dependsOn link, linkTest, pack

dependencies {
  api fileTree(dir: "libs", include: ["bare-kit/classes.jar"])
  api fileTree(dir: "src/main/addons", include: ["*.classes.jar"])
}
