const binding = require('../binding')

exports.STATES = {
  [binding.STATE_OFF]: 'off',
  [binding.STATE_TURNING_ON]: 'turningOn',
  [binding.STATE_ON]: 'on',
  [binding.STATE_TURNING_OFF]: 'turningOff'
}

exports.PROPERTY_READ = binding.PROPERTY_READ
exports.PROPERTY_WRITE_WITHOUT_RESPONSE = binding.PROPERTY_WRITE_WITHOUT_RESPONSE
exports.PROPERTY_WRITE = binding.PROPERTY_WRITE
exports.PROPERTY_NOTIFY = binding.PROPERTY_NOTIFY
exports.PROPERTY_INDICATE = binding.PROPERTY_INDICATE

exports.PERMISSION_READABLE = binding.PERMISSION_READABLE
exports.PERMISSION_WRITEABLE = binding.PERMISSION_WRITEABLE
exports.PERMISSION_READ_ENCRYPTED = binding.PERMISSION_READ_ENCRYPTED
exports.PERMISSION_WRITE_ENCRYPTED = binding.PERMISSION_WRITE_ENCRYPTED

exports.ATT_SUCCESS = binding.ATT_SUCCESS
exports.ATT_INVALID_HANDLE = binding.ATT_INVALID_HANDLE
exports.ATT_READ_NOT_PERMITTED = binding.ATT_READ_NOT_PERMITTED
exports.ATT_WRITE_NOT_PERMITTED = binding.ATT_WRITE_NOT_PERMITTED
exports.ATT_INSUFFICIENT_RESOURCES = binding.ATT_INSUFFICIENT_RESOURCES
exports.ATT_UNLIKELY_ERROR = binding.ATT_UNLIKELY_ERROR
